[package]
name = "day_22"
version = "0.1.0"
authors = ["dgoldsb <dgoldsb@live.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc = { path = "../aoc" }
lazy_static = "1.4.0"
queue = "0.3.0"
